import { Gift } from "@/types";

export async function getGifts(): Promise<Gift[]> {
  return [
    {
      id: "lua-de-mel-contribuicao",
      name: "Contribua com a Lua de Mel",
      description: "Ajude Érika e Franclin a viverem momentos inesquecíveis em sua viagem de lua de mel.",
      suggestedValue: 100,
      category: "lua-de-mel",
      isContribution: true,
      paymentUrl: "https://mpago.la/2bJUdaq",
    },
    {
      id: "jogo-de-jantar",
      name: "Jogo de Jantar",
      description: "Um conjunto completo de pratos para celebrar novas refeições em família.",
      suggestedValue: 250,
      category: "casa",
      paymentUrl: "https://mpago.la/1zzpWK9",
    },
    {
      id: "sofá-retratil",
      name: "Sofá Retrátil",
      description: "Sofá retrátil e reclinável para momentos de conforto e relaxamento.",
      suggestedValue: 1800,
      category: "casa",
      paymentUrl: "https://mpago.la/2CUZBbZ",
    },
    {
      id: "jogo-de-cama",
      name: "Jogo de Cama Casal",
      description: "Conjunto de lençóis e fronhas de algodão egípcio.",
      suggestedValue: 180,
      category: "casa",
      paymentUrl: "https://mpago.la/2ABkFsc",
    },
    {
      id: "conjunto-de-copos",
      name: "Conjunto de Copos",
      description: "Conjunto de copos elegantes para brindar os momentos especiais.",
      suggestedValue: 50,
      category: "casa",
      paymentUrl: "https://mpago.la/1Q9cK5E",
    },
    {
      id: "panelas",
      name: "Conjunto de Panelas",
      description: "Panelas antiaderentes para o novo lar do casal.",
      suggestedValue: 320,
      category: "casa",
      paymentUrl: "https://mpago.la/1vANUAc",
    },
    {
      id: "jantar-romantico",
      name: "Jantar Romântico",
      description: "Um jantar especial para celebrar a primeira semana de casados.",
      suggestedValue: 200,
      category: "lua-de-mel",
      paymentUrl: "https://mpago.la/2cL5Hjz",
    },
    {
      id: "tv-smart",
      name: "TV Smart 55\"",
      description: "Uma TV Smart de 55 polegadas para momentos de entretenimento a dois.",
      suggestedValue: 2500,
      category: "casa",
      paymentUrl: "https://mpago.la/33mGzuB",
    },
    {
      id: "utensilios-de-cozinha",
      name: "Utensílios de Cozinha",
      description: "Conjunto de utensílios essenciais para o dia a dia na cozinha.",
      suggestedValue: 60,
      category: "casa",
      paymentUrl: "https://mpago.la/2HqReku",
    },
    {
      id: "churrasqueira-portatil",
      name: "Churrasqueira Portátil",
      description: "Churrasqueira portátil sem fumaça para momentos de lazer e confraternização.",
      suggestedValue: 700,
      category: "casa",
      paymentUrl: " https://mpago.la/2oLbMVL",
    },  
    {
      id: "caminho-de-mesa",
      name: "Caminho de Mesa",
      description: "Caminho de mesa elegante para decorar a mesa de jantar.",
      suggestedValue: 35,
      category: "casa",
      paymentUrl: "https://mpago.la/1FfsSYf",
    },
    {
      id: "panificadora",
      name: "Panificadora",
      description: "Panificadora automática para preparar pães frescos em casa.",
      suggestedValue: 490,
      category: "casa",
      paymentUrl: "https://mpago.la/2C21pA2",
    }
  ];
}
